version : '3.1'

services:
  db:
    image: mariadb:11.2
    container_name: mariadb_wp_nc
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
    expose:
      - 3306

  wordpress:
    image: wordpress:6.5-php8.1-apache
    container_name: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
  
  nextcloud:
    image: nextcloud:27.1-apache
    container_name: nextcloud
    ports:
      - 8888:80
    environment:
      - MYSQL_PASSWORD=nc_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nc_user
      - MYSQL_HOST=db
    volumes:
      - nextcloud:/var/www/html

volumes:
  db_data:
  wordpress:
  nextcloud: