CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'wp_user'@'%' IDENTIFIED BY 'wp_password';
GRANT ALL PRIVILEGES ON wordpress.* TO 'wp_user'@'%';

CREATE DATABASE IF NOT EXISTS nextcloud;
CREATE USER IF NOT EXISTS 'nc_user'@'%' IDENTIFIED BY 'nc_password';
GRANT ALL PRIVILEGES ON nextcloud.* TO 'nc_user'@'%';

FLUSH PRIVILEGES;